//
// locale_ug.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/ug.json';
import localeData from "react-intl/locale-data/ug.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
