//
// locale_ko.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/ko.json';
import localeData from "react-intl/locale-data/ko.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
