//
// locale_co.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/co.json';
import localeData from "../../app/javascript/mastodon/locales/locale-data/co.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
