//
// locale_kk.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/kk.json';
import localeData from "react-intl/locale-data/kk.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
