//
// locale_is.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/is.json';
import localeData from "react-intl/locale-data/is.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
