//
// locale_lt.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/lt.json';
import localeData from "react-intl/locale-data/lt.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
