//
// locale_si.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/si.json';
import localeData from "react-intl/locale-data/si.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
