//
// locale_da.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/da.json';
import localeData from "react-intl/locale-data/da.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
