//
// locale_tt.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/tt.json';
import localeData from "react-intl/locale-data/tt.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
