//
// locale_zh-CN.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/zh-CN.json';
import localeData from "react-intl/locale-data/zh.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
