//
// locale_pa.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/pa.json';
import localeData from "react-intl/locale-data/pa.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
