//
// locale_kw.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/kw.json';
import localeData from "react-intl/locale-data/kw.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
