//
// locale_sc.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/sc.json';
import localeData from "react-intl/locale-data/sc.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
