//
// locale_ku.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/ku.json';
import localeData from "react-intl/locale-data/ku.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
