//
// locale_zgh.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/zgh.json';
import localeData from "react-intl/locale-data/zgh.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
