//
// locale_et.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/et.json';
import localeData from "react-intl/locale-data/et.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
