//
// locale_af.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/af.json';
import localeData from "react-intl/locale-data/af.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
