//
// locale_tr.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/tr.json';
import localeData from "react-intl/locale-data/tr.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
