//
// locale_nn.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/nn.json';
import localeData from "react-intl/locale-data/nn.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
