//
// locale_lv.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/lv.json';
import localeData from "react-intl/locale-data/lv.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
