//
// locale_gd.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/gd.json';
import localeData from "react-intl/locale-data/gd.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
