//
// locale_kab.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/kab.json';
import localeData from "react-intl/locale-data/kab.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
