//
// locale_ms.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/ms.json';
import localeData from "react-intl/locale-data/ms.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
