//
// locale_bg.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/bg.json';
import localeData from "react-intl/locale-data/bg.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
