//
// locale_mr.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/mr.json';
import localeData from "react-intl/locale-data/mr.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
