//
// locale_kn.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/kn.json';
import localeData from "react-intl/locale-data/kn.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
