//
// locale_mk.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/mk.json';
import localeData from "react-intl/locale-data/mk.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
