//
// locale_ml.js
// automatically generated by generateLocalePacks.js
//
import messages from '../../app/javascript/mastodon/locales/ml.json';
import localeData from "react-intl/locale-data/ml.js";
import { setLocale } from '../../app/javascript/mastodon/locales';
setLocale({messages, localeData});
